version: '3'

services:
  redis:
    image: redis:5-alpine
    ports: [9736:6379]
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [2345:5432]